include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"

  language:
    strict-casts: true
    strict-raw-types: true

  errors:
    always_use_package_imports: ignore
    avoid_positional_boolean_parameters: ignore
    sort_constructors_first: ignore
    unnecessary_await_in_return: ignore
    always_put_required_named_parameters_first: ignore
    prefer_int_literals: ignore
    avoid_redundant_argument_values: ignore
    lines_longer_than_80_chars: ignore
    require_trailing_commas: ignore
    sort_pub_dependencies: ignore
    cascade_invocations: ignore
    directives_ordering: ignore
    omit_local_variable_types: ignore
    deprecated_member_use: ignore
    flutter_style_todos: ignore
    dead_null_aware_expression: ignore
    inference_failure_on_function_invocation: ignore
    inference_failure_on_instance_creation: ignore
    strict_raw_type: ignore
    unused_import: ignore
    unnecessary_lambdas: ignore
    no_default_cases: ignore
    depend_on_referenced_packages: ignore
    unnecessary_breaks: ignore
    curly_braces_in_flow_control_structures: ignore
    avoid_dynamic_calls: ignore
    one_member_abstracts: ignore

linter:
  rules:
    public_member_api_docs: false
    avoid_print: true
