/// Flutter icons Anime_flutter
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Anime_flutter
///      fonts:
///       - asset: fonts/Anime_flutter.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Anime_flutter {
  Anime_flutter._();

  static const _kFontFam = 'Anime_flutter';
  static const String _kFontPkg = null;

  static const IconData imgbin_arrow_font_awesome_computer_icons_png = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
